/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_credit_tests.tc" instead.
 */

#include "s21_calc_tests.h"
START_TEST(s21_credit_0) {
  s21_credit_t res = s21_calculate_annuity(91930155.62, 11, 15.04);
  ck_assert_double_eq_tol(res.monthly_start, 1428069.86, S21_EPS);
  ck_assert_double_eq_tol(res.over, 96575065.90, S21_EPS);
  ck_assert_double_eq_tol(res.total, 188505221.52, S21_EPS);
}
END_TEST

START_TEST(s21_credit_1) {
  s21_credit_t res = s21_calculate_annuity(49042836.76, 10, 21.02);
  ck_assert_double_eq_tol(res.monthly_start, 981180.99, S21_EPS);
  ck_assert_double_eq_tol(res.over, 68698882.04, S21_EPS);
  ck_assert_double_eq_tol(res.total, 117741718.80, S21_EPS);
}
END_TEST

START_TEST(s21_credit_2) {
  s21_credit_t res = s21_calculate_annuity(26162102.37, 48, 13.339);
  ck_assert_double_eq_tol(res.monthly_start, 291313.65, S21_EPS);
  ck_assert_double_eq_tol(res.over, 141634560.03, S21_EPS);
  ck_assert_double_eq_tol(res.total, 167796662.40, S21_EPS);
}
END_TEST

START_TEST(s21_credit_3) {
  s21_credit_t res = s21_calculate_differentiated(91469864.23, 4, 14.719);
  ck_assert_double_eq_tol(res.monthly_start, 3027576.28, S21_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.monthly_end, 1928996.22, S21_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.over, 27487875.69, S21_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.total, 118957739.92, S21_TWO_DECIMALS);
}
END_TEST

START_TEST(s21_credit_4) {
  s21_credit_t res = s21_calculate_differentiated(41071637.5, 21, 3.12723);
  ck_assert_double_eq_tol(res.monthly_start, 270016.40, S21_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.monthly_end, 163407.43, S21_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.over, 13539764.84, S21_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.total, 54611402.34, S21_TWO_DECIMALS);
}
END_TEST

START_TEST(s21_credit_5) {
  s21_credit_t res = s21_calculate_differentiated(6659040.58, 3, 16.50267);

  ck_assert_double_eq_tol(res.monthly_start, 276549.97, S21_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.monthly_end, 187517.14, S21_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.over, 1694167.55, S21_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.total, 8353208.13, S21_TWO_DECIMALS);
}
END_TEST

Suite *s21_credit_tests(void) {
  Suite *s1 = suite_create(PRE_TEST_HEADER "S21_CREDIT" POST_TEST_HEADER);
  TCase *tc1_1 = tcase_create("S21_CREDIT");

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_credit_0);
  tcase_add_test(tc1_1, s21_credit_1);
  tcase_add_test(tc1_1, s21_credit_2);
  tcase_add_test(tc1_1, s21_credit_3);
  tcase_add_test(tc1_1, s21_credit_4);
  tcase_add_test(tc1_1, s21_credit_5);

  return s1;
}
