/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_incorrect_exp_tests.tc" instead.
 */

#include "s21_calc_tests.h"
START_TEST(s21_mismatched_brackets_0) {
  ck_assert_int_eq(s21_exp_to_rpn("(2+3*((5-2)+(3+4)*(2-1)") == NULL, 1);
}
END_TEST

START_TEST(s21_mismatched_brackets_1) {
  ck_assert_int_eq(s21_exp_to_rpn("(2+3)((5-2)+(3+4)(2-1)))") == NULL, 1);
}
END_TEST

START_TEST(s21_mismatched_brackets_2) {
  ck_assert_int_eq(s21_exp_to_rpn("(23^2+45^2-sqrt(9)") == NULL, 1);
}
END_TEST

START_TEST(s21_mismatched_brackets_3) {
  ck_assert_int_eq(s21_exp_to_rpn("(ln((e^3))^2)+log(10^2)") == NULL, 1);
}
END_TEST

START_TEST(s21_mismatched_brackets_4) {
  ck_assert_int_eq(s21_exp_to_rpn("sqrt((16+9)*2^3))") == NULL, 1);
}
END_TEST

START_TEST(s21_mismatched_brackets_5) {
  ck_assert_int_eq(s21_exp_to_rpn("(asin(0.5)^2+atan(1)^2-") == NULL, 1);
}
END_TEST

START_TEST(s21_mismatched_brackets_6) {
  ck_assert_int_eq(s21_exp_to_rpn("((2+sin(30))*2") == NULL, 1);
}
END_TEST

START_TEST(s21_mismatched_brackets_7) {
  ck_assert_int_eq(s21_exp_to_rpn("(sqrt(16+92)*3))") == NULL, 1);
}
END_TEST

START_TEST(s21_mismatched_brackets_8) {
  ck_assert_int_eq(s21_exp_to_rpn("(((2+3)((5-2)+(3+4)(2-1))") == NULL, 1);
}
END_TEST

START_TEST(s21_mismatched_brackets_9) {
  ck_assert_int_eq(s21_exp_to_rpn("sin(30)+cos(60--tan(45)") == NULL, 1);
}
END_TEST
START_TEST(s21_incorrect_unary_0) {
  ck_assert_int_eq(s21_exp_to_rpn("-3*-5+15-4") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_1) {
  ck_assert_int_eq(s21_exp_to_rpn("--4/2") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_2) {
  ck_assert_int_eq(s21_exp_to_rpn("-+10^2") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_3) {
  ck_assert_int_eq(s21_exp_to_rpn("--+3") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_4) {
  ck_assert_int_eq(s21_exp_to_rpn("+-3") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_5) {
  ck_assert_int_eq(s21_exp_to_rpn("5%-2") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_6) {
  ck_assert_int_eq(s21_exp_to_rpn("2*-") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_7) {
  ck_assert_int_eq(s21_exp_to_rpn("--3/42") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_8) {
  ck_assert_int_eq(s21_exp_to_rpn("-3*/5") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_9) {
  ck_assert_int_eq(s21_exp_to_rpn("6+-") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_10) {
  ck_assert_int_eq(s21_exp_to_rpn("7/-") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_11) {
  ck_assert_int_eq(s21_exp_to_rpn("(+-+-8)") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_12) {
  ck_assert_int_eq(s21_exp_to_rpn("-9*-") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_13) {
  ck_assert_int_eq(s21_exp_to_rpn("++10/3") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_14) {
  ck_assert_int_eq(s21_exp_to_rpn("5*-(--3)") == NULL, 1);
}
END_TEST

START_TEST(s21_incorrect_unary_15) {
  ck_assert_int_eq(s21_exp_to_rpn("-4/-") == NULL, 1);
}
END_TEST
START_TEST(s21_several_operators_0) {
  ck_assert_int_eq(s21_exp_to_rpn("2++2") == NULL, 1);
}
END_TEST

START_TEST(s21_several_operators_1) {
  ck_assert_int_eq(s21_exp_to_rpn("3**5+15-4") == NULL, 1);
}
END_TEST

START_TEST(s21_several_operators_2) {
  ck_assert_int_eq(s21_exp_to_rpn("4//2") == NULL, 1);
}
END_TEST

START_TEST(s21_several_operators_3) {
  ck_assert_int_eq(s21_exp_to_rpn("10^^2") == NULL, 1);
}
END_TEST

START_TEST(s21_several_operators_4) {
  ck_assert_int_eq(s21_exp_to_rpn("5%%2") == NULL, 1);
}
END_TEST

START_TEST(s21_several_operators_5) {
  ck_assert_int_eq(s21_exp_to_rpn("sin(30)+cos(60)++tan(45)") == NULL, 1);
}
END_TEST

START_TEST(s21_several_operators_6) {
  ck_assert_int_eq(s21_exp_to_rpn("acos(0.5)++asin(0.5)+atan(1)") == NULL, 1);
}
END_TEST

START_TEST(s21_several_operators_7) {
  ck_assert_int_eq(s21_exp_to_rpn("(2+3)((5-2))+(3+4)(2-1)") == NULL, 1);
}
END_TEST

START_TEST(s21_several_operators_8) {
  ck_assert_int_eq(s21_exp_to_rpn("sqrt(16+9*2)*3)/4") == NULL, 1);
}
END_TEST

START_TEST(s21_several_operators_9) {
  ck_assert_int_eq(s21_exp_to_rpn("ln(2)+log(10)++log(2)") == NULL, 1);
}
END_TEST
START_TEST(s21_functions_without_parentheses_0) {
  ck_assert_int_eq(s21_exp_to_rpn("cos30+sin45*tan60") == NULL, 1);
}
END_TEST

START_TEST(s21_functions_without_parentheses_1) {
  ck_assert_int_eq(s21_exp_to_rpn("sqrt16+sqrt9*2") == NULL, 1);
}
END_TEST

START_TEST(s21_functions_without_parentheses_2) {
  ck_assert_int_eq(s21_exp_to_rpn("ln2+log10-acos0.5") == NULL, 1);
}
END_TEST

START_TEST(s21_functions_without_parentheses_3) {
  ck_assert_int_eq(s21_exp_to_rpn("sin30*cos60+tan45") == NULL, 1);
}
END_TEST

START_TEST(s21_functions_without_parentheses_4) {
  ck_assert_int_eq(s21_exp_to_rpn("acos0.5+asin0.5+atan1") == NULL, 1);
}
END_TEST

START_TEST(s21_functions_without_parentheses_5) {
  ck_assert_int_eq(s21_exp_to_rpn("sqrt16+9*2-3") == NULL, 1);
}
END_TEST

START_TEST(s21_functions_without_parentheses_6) {
  ck_assert_int_eq(s21_exp_to_rpn("ln(e^5)+log102") == NULL, 1);
}
END_TEST

START_TEST(s21_functions_without_parentheses_7) {
  ck_assert_int_eq(s21_exp_to_rpn("acos0.5+asin0.5") == NULL, 1);
}
END_TEST

START_TEST(s21_functions_without_parentheses_8) {
  ck_assert_int_eq(s21_exp_to_rpn("cos45*sin30+tan60") == NULL, 1);
}
END_TEST

START_TEST(s21_functions_without_parentheses_9) {
  ck_assert_int_eq(s21_exp_to_rpn("sqrt16+sqrt(9*2)") == NULL, 1);
}
END_TEST
START_TEST(s21_expression_ends_on_operator_0) {
  ck_assert_int_eq(s21_exp_to_rpn("cos(30)+sin(45)*tan(60)+cos") == NULL, 1);
}
END_TEST
START_TEST(s21_two_decimal_points_0) {
  ck_assert_int_eq(s21_exp_to_rpn("2+2.25+3.25.48-3") == NULL, 1);
}
END_TEST

START_TEST(s21_two_decimal_points_1) {
  ck_assert_int_eq(s21_exp_to_rpn("1..5 + 2") == NULL, 1);
}
END_TEST

START_TEST(s21_two_decimal_points_2) {
  ck_assert_int_eq(s21_exp_to_rpn("3.4.5 - 1") == NULL, 1);
}
END_TEST

START_TEST(s21_two_decimal_points_3) {
  ck_assert_int_eq(s21_exp_to_rpn("6..7 * 4") == NULL, 1);
}
END_TEST

START_TEST(s21_two_decimal_points_4) {
  ck_assert_int_eq(s21_exp_to_rpn("2 / 3..1") == NULL, 1);
}
END_TEST

START_TEST(s21_two_decimal_points_5) {
  ck_assert_int_eq(s21_exp_to_rpn("sin(30.2.3)") == NULL, 1);
}
END_TEST

START_TEST(s21_two_decimal_points_6) {
  ck_assert_int_eq(s21_exp_to_rpn("cos(4..56)") == NULL, 1);
}
END_TEST

START_TEST(s21_two_decimal_points_7) {
  ck_assert_int_eq(s21_exp_to_rpn("tan(5..89)") == NULL, 1);
}
END_TEST

START_TEST(s21_two_decimal_points_8) {
  ck_assert_int_eq(s21_exp_to_rpn("54..23 + sqrt(16)") == NULL, 1);
}
END_TEST

START_TEST(s21_two_decimal_points_9) {
  ck_assert_int_eq(s21_exp_to_rpn("log(10..10)") == NULL, 1);
}
END_TEST

START_TEST(s21_two_decimal_points_10) {
  ck_assert_int_eq(s21_exp_to_rpn("ln(23..34)") == NULL, 1);
}
END_TEST
START_TEST(s21_loose_decimal_points_0) {
  ck_assert_int_eq(s21_exp_to_rpn("cos(30).sin(5)") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_1) {
  ck_assert_int_eq(s21_exp_to_rpn("cos(30).5+2") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_2) {
  ck_assert_int_eq(s21_exp_to_rpn(".5-8") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_3) {
  ck_assert_int_eq(s21_exp_to_rpn("5+7-2^2.") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_4) {
  ck_assert_int_eq(s21_exp_to_rpn(". + 5") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_5) {
  ck_assert_int_eq(s21_exp_to_rpn("6 * .") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_6) {
  ck_assert_int_eq(s21_exp_to_rpn("sqrt(.)") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_7) {
  ck_assert_int_eq(s21_exp_to_rpn(". / 3") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_8) {
  ck_assert_int_eq(s21_exp_to_rpn("sin(.)") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_9) {
  ck_assert_int_eq(s21_exp_to_rpn("log(.)") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_10) {
  ck_assert_int_eq(s21_exp_to_rpn("2 + . * 4") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_11) {
  ck_assert_int_eq(s21_exp_to_rpn("- 2 / .") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_12) {
  ck_assert_int_eq(s21_exp_to_rpn("tan(45).") == NULL, 1);
}
END_TEST

START_TEST(s21_loose_decimal_points_13) {
  ck_assert_int_eq(s21_exp_to_rpn(".sin(45)") == NULL, 1);
}
END_TEST

Suite *s21_incorrect_exp_tests(void) {
  Suite *s1 = suite_create(PRE_TEST_HEADER "S21_INCORRECT" POST_TEST_HEADER);
  TCase *tc1_1 = tcase_create("S21_MISMATCHED_BRACKETS");
  TCase *tc1_2 = tcase_create("S21_INCORRECT_UNARY");
  TCase *tc1_3 = tcase_create("S21_SEVERAL_OPERATORS");
  TCase *tc1_4 = tcase_create("S21_FUNCTIONS_WITHOUT_PARENTHESES");
  TCase *tc1_5 = tcase_create("S21_EXPRESSION_ENDS_ON_OPERATOR");
  TCase *tc1_6 = tcase_create("S21_TWO_DECIMAL_POINTS");
  TCase *tc1_7 = tcase_create("S21_LOOSE_DECIMAL_POINTS");

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_mismatched_brackets_0);
  tcase_add_test(tc1_1, s21_mismatched_brackets_1);
  tcase_add_test(tc1_1, s21_mismatched_brackets_2);
  tcase_add_test(tc1_1, s21_mismatched_brackets_3);
  tcase_add_test(tc1_1, s21_mismatched_brackets_4);
  tcase_add_test(tc1_1, s21_mismatched_brackets_5);
  tcase_add_test(tc1_1, s21_mismatched_brackets_6);
  tcase_add_test(tc1_1, s21_mismatched_brackets_7);
  tcase_add_test(tc1_1, s21_mismatched_brackets_8);
  tcase_add_test(tc1_1, s21_mismatched_brackets_9);
  suite_add_tcase(s1, tc1_2);
  tcase_add_test(tc1_2, s21_incorrect_unary_0);
  tcase_add_test(tc1_2, s21_incorrect_unary_1);
  tcase_add_test(tc1_2, s21_incorrect_unary_2);
  tcase_add_test(tc1_2, s21_incorrect_unary_3);
  tcase_add_test(tc1_2, s21_incorrect_unary_4);
  tcase_add_test(tc1_2, s21_incorrect_unary_5);
  tcase_add_test(tc1_2, s21_incorrect_unary_6);
  tcase_add_test(tc1_2, s21_incorrect_unary_7);
  tcase_add_test(tc1_2, s21_incorrect_unary_8);
  tcase_add_test(tc1_2, s21_incorrect_unary_9);
  tcase_add_test(tc1_2, s21_incorrect_unary_10);
  tcase_add_test(tc1_2, s21_incorrect_unary_11);
  tcase_add_test(tc1_2, s21_incorrect_unary_12);
  tcase_add_test(tc1_2, s21_incorrect_unary_13);
  tcase_add_test(tc1_2, s21_incorrect_unary_14);
  tcase_add_test(tc1_2, s21_incorrect_unary_15);
  suite_add_tcase(s1, tc1_3);
  tcase_add_test(tc1_3, s21_several_operators_0);
  tcase_add_test(tc1_3, s21_several_operators_1);
  tcase_add_test(tc1_3, s21_several_operators_2);
  tcase_add_test(tc1_3, s21_several_operators_3);
  tcase_add_test(tc1_3, s21_several_operators_4);
  tcase_add_test(tc1_3, s21_several_operators_5);
  tcase_add_test(tc1_3, s21_several_operators_6);
  tcase_add_test(tc1_3, s21_several_operators_7);
  tcase_add_test(tc1_3, s21_several_operators_8);
  tcase_add_test(tc1_3, s21_several_operators_9);
  suite_add_tcase(s1, tc1_4);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_0);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_1);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_2);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_3);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_4);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_5);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_6);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_7);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_8);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_9);
  suite_add_tcase(s1, tc1_5);
  tcase_add_test(tc1_5, s21_expression_ends_on_operator_0);
  suite_add_tcase(s1, tc1_6);
  tcase_add_test(tc1_6, s21_two_decimal_points_0);
  tcase_add_test(tc1_6, s21_two_decimal_points_1);
  tcase_add_test(tc1_6, s21_two_decimal_points_2);
  tcase_add_test(tc1_6, s21_two_decimal_points_3);
  tcase_add_test(tc1_6, s21_two_decimal_points_4);
  tcase_add_test(tc1_6, s21_two_decimal_points_5);
  tcase_add_test(tc1_6, s21_two_decimal_points_6);
  tcase_add_test(tc1_6, s21_two_decimal_points_7);
  tcase_add_test(tc1_6, s21_two_decimal_points_8);
  tcase_add_test(tc1_6, s21_two_decimal_points_9);
  tcase_add_test(tc1_6, s21_two_decimal_points_10);
  suite_add_tcase(s1, tc1_7);
  tcase_add_test(tc1_7, s21_loose_decimal_points_0);
  tcase_add_test(tc1_7, s21_loose_decimal_points_1);
  tcase_add_test(tc1_7, s21_loose_decimal_points_2);
  tcase_add_test(tc1_7, s21_loose_decimal_points_3);
  tcase_add_test(tc1_7, s21_loose_decimal_points_4);
  tcase_add_test(tc1_7, s21_loose_decimal_points_5);
  tcase_add_test(tc1_7, s21_loose_decimal_points_6);
  tcase_add_test(tc1_7, s21_loose_decimal_points_7);
  tcase_add_test(tc1_7, s21_loose_decimal_points_8);
  tcase_add_test(tc1_7, s21_loose_decimal_points_9);
  tcase_add_test(tc1_7, s21_loose_decimal_points_10);
  tcase_add_test(tc1_7, s21_loose_decimal_points_11);
  tcase_add_test(tc1_7, s21_loose_decimal_points_12);
  tcase_add_test(tc1_7, s21_loose_decimal_points_13);

  return s1;
}
