/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_incorrect_exp_tests.tc" instead.
 */

#include "s21_calc_tests.h"

START_TEST(s21_mismatched_brackets_0) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("(2+3*((5-2)+(3+4)*(2-1)", &p), 0);
}
END_TEST

START_TEST(s21_mismatched_brackets_1) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("(2+3)((5-2)+(3+4)(2-1)))", &p), 0);
}
END_TEST

START_TEST(s21_mismatched_brackets_2) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("(23^2+45^2-sqrt(9)", &p), 0);
}
END_TEST

START_TEST(s21_mismatched_brackets_3) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("(ln((e^3))^2)+log(10^2)", &p), 0);
}
END_TEST

START_TEST(s21_mismatched_brackets_4) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("sqrt((16+9)*2^3))", &p), 0);
}
END_TEST

START_TEST(s21_mismatched_brackets_5) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("(asin(0.5)^2+atan(1)^2-", &p), 0);
}
END_TEST

START_TEST(s21_mismatched_brackets_6) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("((2+sin(30))*2", &p), 0);
}
END_TEST

START_TEST(s21_mismatched_brackets_7) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("(sqrt(16+92)*3))", &p), 0);
}
END_TEST

START_TEST(s21_mismatched_brackets_8) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("(((2+3)((5-2)+(3+4)(2-1))", &p), 0);
}
END_TEST

START_TEST(s21_mismatched_brackets_9) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("sin(30)+cos(60--tan(45)", &p), 0);
}
END_TEST
START_TEST(s21_incorrect_unary_0) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("-3*-5+15-4", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_1) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("--4/2", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_2) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("-+10^2", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_3) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("--+3", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_4) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("+-3", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_5) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("5%-2", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_6) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("2*-", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_7) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("--3/42", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_8) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("-3*/5", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_9) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("6+-", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_10) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("7/-", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_11) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("(+-+-8)", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_12) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("-9*-", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_13) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("++10/3", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_14) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("5*-(--3)", &p), 0);
}
END_TEST

START_TEST(s21_incorrect_unary_15) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("-4/-", &p), 0);
}
END_TEST
START_TEST(s21_several_operators_0) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("2++2", &p), 0);
}
END_TEST

START_TEST(s21_several_operators_1) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("3**5+15-4", &p), 0);
}
END_TEST

START_TEST(s21_several_operators_2) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("4//2", &p), 0);
}
END_TEST

START_TEST(s21_several_operators_3) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("10^^2", &p), 0);
}
END_TEST

START_TEST(s21_several_operators_4) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("5%%2", &p), 0);
}
END_TEST

START_TEST(s21_several_operators_5) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("sin(30)+cos(60)++tan(45)", &p), 0);
}
END_TEST

START_TEST(s21_several_operators_6) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("acos(0.5)++asin(0.5)+atan(1)", &p), 0);
}
END_TEST

START_TEST(s21_several_operators_7) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("(2+3)((5-2))+(3+4)(2-1)", &p), 0);
}
END_TEST

START_TEST(s21_several_operators_8) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("sqrt(16+9*2)*3)/4", &p), 0);
}
END_TEST

START_TEST(s21_several_operators_9) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("ln(2)+log(10)++log(2)", &p), 0);
}
END_TEST
START_TEST(s21_functions_without_parentheses_0) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("cos30+sin45*tan60", &p), 0);
}
END_TEST

START_TEST(s21_functions_without_parentheses_1) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("sqrt16+sqrt9*2", &p), 0);
}
END_TEST

START_TEST(s21_functions_without_parentheses_2) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("ln2+log10-acos0.5", &p), 0);
}
END_TEST

START_TEST(s21_functions_without_parentheses_3) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("sin30*cos60+tan45", &p), 0);
}
END_TEST

START_TEST(s21_functions_without_parentheses_4) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("acos0.5+asin0.5+atan1", &p), 0);
}
END_TEST

START_TEST(s21_functions_without_parentheses_5) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("sqrt16+9*2-3", &p), 0);
}
END_TEST

START_TEST(s21_functions_without_parentheses_6) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("ln(e^5)+log102", &p), 0);
}
END_TEST

START_TEST(s21_functions_without_parentheses_7) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("acos0.5+asin0.5", &p), 0);
}
END_TEST

START_TEST(s21_functions_without_parentheses_8) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("cos45*sin30+tan60", &p), 0);
}
END_TEST

START_TEST(s21_functions_without_parentheses_9) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("sqrt16+sqrt(9*2)", &p), 0);
}
END_TEST
START_TEST(s21_expression_ends_on_operator_0) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("cos(30)+sin(45)*tan(60)+cos", &p), 0);
}
END_TEST
START_TEST(s21_two_decimal_points_0) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("2+2.25+3.25.48-3", &p), 0);
}
END_TEST
START_TEST(s21_loose_decimal_points_0) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("cos(30).sin(5)", &p), 0);
}
END_TEST

START_TEST(s21_loose_decimal_points_1) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("cos(30).5+2", &p), 0);
}
END_TEST

START_TEST(s21_loose_decimal_points_2) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate(".5-8", &p), 0);
}
END_TEST

START_TEST(s21_loose_decimal_points_3) {
  char out[MAX_EXP_LEN + 1] = {0};
  char* p = out;
  ck_assert_int_eq(s21_validate("5+7-2^2.", &p), 0);
}
END_TEST

Suite* s21_incorrect_exp_tests(void) {
  Suite* s1 = suite_create(PRE_TEST_HEADER "S21_INCORRECT" POST_TEST_HEADER);
  TCase* tc1_1 = tcase_create("S21_MISMATCHED_BRACKETS");
  TCase* tc1_2 = tcase_create("S21_INCORRECT_UNARY");
  TCase* tc1_3 = tcase_create("S21_SEVERAL_OPERATORS");
  TCase* tc1_4 = tcase_create("S21_FUNCTIONS_WITHOUT_PARENTHESES");
  TCase* tc1_5 = tcase_create("S21_EXPRESSION_ENDS_ON_OPERATOR");
  TCase* tc1_6 = tcase_create("S21_TWO_DECIMAL_POINTS");
  TCase* tc1_7 = tcase_create("S21_LOOSE_DECIMAL_POINTS");

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_mismatched_brackets_0);
  tcase_add_test(tc1_1, s21_mismatched_brackets_1);
  tcase_add_test(tc1_1, s21_mismatched_brackets_2);
  tcase_add_test(tc1_1, s21_mismatched_brackets_3);
  tcase_add_test(tc1_1, s21_mismatched_brackets_4);
  tcase_add_test(tc1_1, s21_mismatched_brackets_5);
  tcase_add_test(tc1_1, s21_mismatched_brackets_6);
  tcase_add_test(tc1_1, s21_mismatched_brackets_7);
  tcase_add_test(tc1_1, s21_mismatched_brackets_8);
  tcase_add_test(tc1_1, s21_mismatched_brackets_9);
  suite_add_tcase(s1, tc1_2);
  tcase_add_test(tc1_2, s21_incorrect_unary_0);
  tcase_add_test(tc1_2, s21_incorrect_unary_1);
  tcase_add_test(tc1_2, s21_incorrect_unary_2);
  tcase_add_test(tc1_2, s21_incorrect_unary_3);
  tcase_add_test(tc1_2, s21_incorrect_unary_4);
  tcase_add_test(tc1_2, s21_incorrect_unary_5);
  tcase_add_test(tc1_2, s21_incorrect_unary_6);
  tcase_add_test(tc1_2, s21_incorrect_unary_7);
  tcase_add_test(tc1_2, s21_incorrect_unary_8);
  tcase_add_test(tc1_2, s21_incorrect_unary_9);
  tcase_add_test(tc1_2, s21_incorrect_unary_10);
  tcase_add_test(tc1_2, s21_incorrect_unary_11);
  tcase_add_test(tc1_2, s21_incorrect_unary_12);
  tcase_add_test(tc1_2, s21_incorrect_unary_13);
  tcase_add_test(tc1_2, s21_incorrect_unary_14);
  tcase_add_test(tc1_2, s21_incorrect_unary_15);
  suite_add_tcase(s1, tc1_3);
  tcase_add_test(tc1_3, s21_several_operators_0);
  tcase_add_test(tc1_3, s21_several_operators_1);
  tcase_add_test(tc1_3, s21_several_operators_2);
  tcase_add_test(tc1_3, s21_several_operators_3);
  tcase_add_test(tc1_3, s21_several_operators_4);
  tcase_add_test(tc1_3, s21_several_operators_5);
  tcase_add_test(tc1_3, s21_several_operators_6);
  tcase_add_test(tc1_3, s21_several_operators_7);
  tcase_add_test(tc1_3, s21_several_operators_8);
  tcase_add_test(tc1_3, s21_several_operators_9);
  suite_add_tcase(s1, tc1_4);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_0);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_1);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_2);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_3);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_4);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_5);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_6);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_7);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_8);
  tcase_add_test(tc1_4, s21_functions_without_parentheses_9);
  suite_add_tcase(s1, tc1_5);
  tcase_add_test(tc1_5, s21_expression_ends_on_operator_0);
  suite_add_tcase(s1, tc1_6);
  tcase_add_test(tc1_6, s21_two_decimal_points_0);
  suite_add_tcase(s1, tc1_7);
  tcase_add_test(tc1_7, s21_loose_decimal_points_0);
  tcase_add_test(tc1_7, s21_loose_decimal_points_1);
  tcase_add_test(tc1_7, s21_loose_decimal_points_2);
  tcase_add_test(tc1_7, s21_loose_decimal_points_3);

  return s1;
}
