/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "scp_credit_tests.tc" instead.
 */

#include "scp_calc_tests.h"
START_TEST(scp_credit_0) {
  scp_credit_t res = scp_calculate_annuity(91930155.62, 11, 15.04);
  ck_assert_double_eq_tol(res.monthly_start, 1428069.86, SCP_EPS);
  ck_assert_double_eq_tol(res.over, 96575065.90, SCP_EPS);
  ck_assert_double_eq_tol(res.total, 188505221.52, SCP_EPS);
}
END_TEST

START_TEST(scp_credit_1) {
  scp_credit_t res = scp_calculate_annuity(49042836.76, 10, 21.02);
  ck_assert_double_eq_tol(res.monthly_start, 981180.99, SCP_EPS);
  ck_assert_double_eq_tol(res.over, 68698882.04, SCP_EPS);
  ck_assert_double_eq_tol(res.total, 117741718.80, SCP_EPS);
}
END_TEST

START_TEST(scp_credit_2) {
  scp_credit_t res = scp_calculate_annuity(26162102.37, 48, 13.339);
  ck_assert_double_eq_tol(res.monthly_start, 291313.65, SCP_EPS);
  ck_assert_double_eq_tol(res.over, 141634560.03, SCP_EPS);
  ck_assert_double_eq_tol(res.total, 167796662.40, SCP_EPS);
}
END_TEST

START_TEST(scp_credit_3) {
  scp_credit_t res = scp_calculate_differentiated(91469864.23, 4, 14.719);
  ck_assert_double_eq_tol(res.monthly_start, 3027576.28, SCP_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.monthly_end, 1928996.22, SCP_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.over, 27487875.69, SCP_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.total, 118957739.92, SCP_TWO_DECIMALS);
}
END_TEST

START_TEST(scp_credit_4) {
  scp_credit_t res = scp_calculate_differentiated(41071637.5, 21, 3.12723);
  ck_assert_double_eq_tol(res.monthly_start, 270016.40, SCP_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.monthly_end, 163407.43, SCP_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.over, 13539764.84, SCP_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.total, 54611402.34, SCP_TWO_DECIMALS);
}
END_TEST

START_TEST(scp_credit_5) {
  scp_credit_t res = scp_calculate_differentiated(6659040.58, 3, 16.50267);

  ck_assert_double_eq_tol(res.monthly_start, 276549.97, SCP_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.monthly_end, 187517.14, SCP_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.over, 1694167.55, SCP_TWO_DECIMALS);
  ck_assert_double_eq_tol(res.total, 8353208.13, SCP_TWO_DECIMALS);
}
END_TEST

Suite *scp_credit_tests(void) {
  Suite *s1 = suite_create(PRE_TEST_HEADER "SCP_CREDIT" POST_TEST_HEADER);
  TCase *tc1_1 = tcase_create("SCP_CREDIT");

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, scp_credit_0);
  tcase_add_test(tc1_1, scp_credit_1);
  tcase_add_test(tc1_1, scp_credit_2);
  tcase_add_test(tc1_1, scp_credit_3);
  tcase_add_test(tc1_1, scp_credit_4);
  tcase_add_test(tc1_1, scp_credit_5);

  return s1;
}
